### PR TITLE
Dragdrop

### PR DESCRIPTION
**Pull request by ElectrifyPowr**
- Right bar implementation
- Drag & drop of map elements in map building mode implementation
- Play & Pause buttons in bottom bar

### CODE REVIEW

**Review by Lugges991 — APPROVED** [review]
Good job, Patrick!

**Review by Lugges991 — APPROVED** [review]
Nice!

**Review by KasparasGud — COMMENTED** [review]
Looks sexy<3

**Review by KasparasGud — APPROVED** [review]
Lets gooo

**Pull request merged**
